---
title: "Getting & Cleaning Data PA"
author: "Hsin Chih Chen"
date: "2022/4/1"
output: html_document
---

---
title: "Getting & Cleaning Data PA"
author: "Hsin Chih Chen"
date: "2022/4/1"
output: html_document
---

### Introduction

The purpose of the assignment will have the following objectives </br>

1. Merges the training and test sets to create one data set. </br>
2. Extracts only measurement on the mean and stdev. </br>
3. Use descriptive activity names to name activities in dataset. </br>
4. Appropriately labels data set with descriptive variable names. </br>
5. Create an independent tidy data set with the average of each variable for each activity and each subject. </br>


### Data Set Information
The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. </br>

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. </br>

### Attribute Information
For each record in the dataset it is provided: </br>
- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration. </br>
- Triaxial Angular velocity from the gyroscope. </br>
- A 561-feature vector with time and frequency domain variables. </br>
- Its activity label. </br>
- An identifier of the subject who carried out the experiment. </br>

### Code Analysis Chunk

```{R Preliminary File Allocation, warning = FALSE, message = FALSE}
# Load Packages and Directly Download Files
library('data.table')
library('reshape2')

path <- getwd()
url <- "http://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(url, file.path(path, 'project3.zip'))
unzip(zipfile = 'project3.zip')
```

```{R Activity Loading}
# Load Activity Labels & Name respectively
activityL <- fread(file.path(path, "UCI HAR Dataset/activity_labels.txt")
              ,col.names = c('classLabels', 'activityName'))

# Load Features Labels & Names respectively
feat <- fread(file.path(path, "UCI HAR Dataset/features.txt")
              ,col.names = c('index','featureNames'))

# Obtain Wanted Features and Measurements
featWanted <- grep("(mean|std)\\(\\)", feat[, featureNames])
meas <- feat[featWanted, featureNames]
meas <- gsub('[()]', '', meas)

# Load train datasets
train <- fread(file.path(path,"UCI HAR Dataset/train/X_train.txt"))[, featWanted, with = FALSE]
setnames(train, colnames(train), meas)
trainAct <- fread(file.path(path, 'UCI HAR Dataset/train/y_train.txt'), col.names = c('Activity'))
trainSub <- fread(file.path(path, 'UCI HAR Dataset/train/subject_train.txt'), col.names = c('SubjectNum'))
train <- cbind(trainSub, trainAct, train)

# Load test datasets
test <- fread(file.path(path, 'UCI HAR Dataset/test/X_test.txt'))[, featWanted, with = FALSE]
setnames(test, colnames(test), meas)
testAct <- fread(file.path(path, 'UCI HAR Dataset/test/y_test.txt'), col.names = c('Activity'))
testSub <- fread(file.path(path, 'UCI HAR Dataset/test/subject_test.txt'), col.names = c('SubjectNum'))
test <- cbind(testSub, testAct, test)
```

```{R Data Merge & Conversion}
# Merge Both Test & Train dataset
combi <- rbind(train, test)

# Convert classLabels to activityName
combi[['Activity']] <- factor(combi[, Activity]
                              ,levels = activityL[['classLabels']] 
                              ,labels = activityL[['activityName']])

combi[['SubjectNum']] <-as.factor(combi[, SubjectNum])
combi <- reshape2::melt(data = combi, id = c('SubjectNum','Activity'))
combi <- reshape2::dcast(data = combi, SubjectNum + Activity ~ variable, fun.aggregate = mean)
```

```{R Data Export}
# Export the Text File for Data
fwrite(x = combi, file = "tidyData.txt", quote = FALSE)
```